name: CD Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Update to your project's version

    - name: Build and Publish
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to MonsterASP.NET
      uses: webapps-deploy/webapps-deploy@v2
      with:
        app-name: 'site90440'
        publish-profile: 'site90440'
        slot-name: 'production'
        package: './publish'
        publish-profile-password: ${{ secrets.WEBDEPLOY_PASSWORD }}
        publish-url: 'https://site90440.siteasp.net:8172/msdeploy.axd'
        site-name: 'site90440'
        user-name: 'site90440'
